development:

  adapter: postgresql
  encoding: unicode
  username: rails2
  password: rails2
  host: 127.0.0.1
  port: 5432
  database: devd
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  username: rails2
  password: rails2
  host: 127.0.0.1
  port: 5432
  database: devt
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  username: rails2
  password: rails2
  host: 127.0.0.1
  port: 5432
  database: devp
  pool: 5
  timeout: 5000